### ISSUE TITLE
CODEOWNERS can live in `docs/` or `.github/` as well

### ISSUE THREAD

**Issue by halostatue** [joelparkerhenderson/github-special-files-and-paths#16]
I’m not sure how much this applies to the rest of the files mentioned, but on `CODEOWNERS` at least, it can live in any of, the root, `docs/`, and `.github/`.

**Comment by joelparkerhenderson** [comment]
Yes. In the README, near the top, there's this...

GitHub special files are typically located at the repository top level or in special paths:

    /.github is a hidden dot file directory.

    /docs is a typical documentation directory.

**Comment by halostatue** [comment]
No, I was looking at the `CODEOWNERS` entry itself and not noticing that mention there and had missed the bit at the top. The information I was looking for (I’m mentioning this repo in some internal documentation that I’m writing) is in the README, but not where I expected it to be.

I think the only minor suggestion I would have is, since not all files can live in all locations, marking the different file entries as `root`, `.github`, `docs/`, and possibly even `external` (for ones that can be pulled from `.github` or `.github-private` repos) in the section of that document would be useful. It would be extremely repetitive.

What you’ve provided here is a good resource that I wish that GitHub itself provided in a single location ("About the `.github` directory" or "Special Files and Repositories for GitHub"), and for that I thank you. You can close this or choose it for that feature suggestion at your leisure, but the information I wanted is present.

**Comment by joelparkerhenderson** [comment]
Thank you for your good explanation. I'll add the info now that I understand. It might feel a bit repetitive, though I think that's OK for this need because it can help people.

**Comment by halostatue** [comment]
It looks great. Thank you again for filling in on this missing GitHub documentation.
