### ISSUE TITLE
Citation and License files don't work in .docs

### ISSUE THREAD

**Issue by jtwaleson** [joelparkerhenderson/github-special-files-and-paths#17]
I've been trying to put LICENSE and CITATION.cff files in /docs but it didn't show on the main project page. I think these have to be in the root directory. Using symlinks to /docs does work.

**Comment by joelparkerhenderson** [comment]
Oooh, this is good new info, thank you. Would you like to do a pull request to adjust the page the way you feel is best?

Or if you prefer, I can take a look, likely this week, and fix the gap.
