### ISSUE TITLE
README also works in `.docs`

### ISSUE THREAD

**Issue by Malix-off** [joelparkerhenderson/github-special-files-and-paths#19]
And maybe in `.github` too, please review

**Comment by joelparkerhenderson** [comment]
Can you explain more about what you mean that "README also works"?

When you write "please review", what are you asking me to review? For example, is there a documentation update to the special files, or do wish to do a pull request, or something else?

**Comment by Malix-off** [comment]
> Can you explain more about what you mean that "README also works"?

As in "detected by GitHub"

> When you write "please review", what are you asking me to review?

For myself when I will reach my computer the next time (unsure when)

Sorry about that

**Comment by Malix-off** [comment]
I just tested it, here is the order by which it is detected:
1. `/.github`
2. `/docs`
3. `/` (root)

It is also written in [their official documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes)

**Comment by joelparkerhenderson** [comment]
Thank you, that additional info helps. Fixed.

https://github.com/joelparkerhenderson/github-special-files-and-paths/commit/9c65af5b4b417cceb7507a8f92e8f2e86c581082
