### ISSUE TITLE
Add `dependabot.yml` to the list

### ISSUE THREAD

**Issue by atombrella** [joelparkerhenderson/github-special-files-and-paths#8]
Thank you for this overview. GitHub's vulnerability scanner is not part of the overview. `.github/dependabot.yml` will enable PRs from dependabot with updates of vulnerable packages.
 
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#configuration-options-for-updates

**Comment by joelparkerhenderson** [comment]
Done. Thank you for this!
